### ISSUE TITLE
H&L: NotesDialog: Change button names to site, hook note

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/pyFieldSoftware#80] opened 2020-03-10 17:36 UTC

**Comment by johnharms-NOAA** [comment] 2020-07-09 23:42
This may be the same thing as item #78

**Comment by SaOgaz-NOAA** [comment] 2020-09-04 23:00
I see two places more notes:

so change this one to "Site Notes"

![image](https://user-images.githubusercontent.com/54552385/92290061-9db4dd00-eec7-11ea-91e2-67252e592ecb.png)

and this one to "Hook Notes"?

![image](https://user-images.githubusercontent.com/54552385/92290079-adccbc80-eec7-11ea-8a2a-1ff84dbdca87.png)

**Comment by johnharms-NOAA** [comment] 2020-09-04 23:45
Just sent you a longish email about this, but yes, what you say captures the gist of what we want. However, I think that the Notes button in your first image is still really just a fish-level note even though it is on that top-level screen. I don't think the SQLite database has a field set up to accommodate site-level notes made from the Cutter station.  In your second image, I would suggest using "Fish Notes" rather than "Hook Notes" as those are discrete and separate levels in the hierarchy. Generally, the HookMatrix person would log hook-level notes which relate more toward the hook/gear results than the actual fish itself.  So I think we might need to first make sure the database schema includes the correct fields to receive notes at the various levels.  Basically, the HookMatrix workstation would need to be able to write notes at 3 different levels in the database:  Site, Angler/Drop, and Hook with the button name indicating the level.  The Cutter workstation needs to be able to record notes at 2 levels:  Site and Fish.  So, it would seem like the database needs to either have 5 unique notes fields to accommodate that (HM-Site, HM-Angler/Drop, HM-Hook, Cutter-Site, Cutter-Fish), or alternatively, 4 notes fields (Site, Angler/Drop, Hook, Fish) - but then for the Site-Level notes, some way to capture whether it came from the HookMatrix or Cutter station.  This is in addition to the 4 notes fields at the Galley station which are in good shape and I think are fine as is.

**Comment by SaOgaz-NOAA** [comment] 2020-09-14 17:12
Hi @johnharms-NOAA, I see you closed this ticket. Do we not need this change any more?

**Comment by johnharms-NOAA** [comment] 2020-09-14 19:08
I think I may have inadvertently closed this issue by pressing "close and comment" instead of just "comment" - it should probably still remain open until we verify that it all works as intended. And as a general question about GitHub best practices at least as far we're using it for survey software - at what point should we close issues with regard to testing/troubleshooting the various fixes and features that are implemented?

**Closed** 2020-09-15 17:55 UTC
Labels: CutterStation, H&L, high-priority
