### ISSUE TITLE
H&L: DropsScreen: seconds can read 60 instead of turning over to the next minute

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/pyFieldSoftware#42] opened 2020-03-10 17:35 UTC

**Comment by johnharms-NOAA** [comment] 2020-09-05 00:33
Possibly an "easy" issue.  It doesn't happen all the time, but there are frequently situations where the seconds places of the HookMatrix angler times roll over very briefly to MM:60 rather than rolling over to the next minute and MM:00, so 00:60 instead of 01:00;  01:60 instead of 02:00; etc.  When this happens and the user presses one of the time waypoint buttons, that XX:60 will be written to the database.

**Comment by johnharms-NOAA** [comment] 2020-09-05 00:48
Note that this issue appears to be a duplicate of #89, so #89 has now been closed.

**Comment by jimfellows-NOAA** [comment] 2020-09-05 20:05
function formatTime in DropsScreen.qml rounds seconds after dividing total time by 60 and taking remainder.  Using the Math.floor function instead should ensure that seconds will always remain below 60.

_Original Function Example:_
Say you have 119.7 seconds elapsed, the function was doing the following:
Minutes = 119.7 / 60 = 1.995 = Math.floor(1.995) = 1
Seconds = 119.7 % 60 = 59.7 = Math.**round**(59.7)) = 60
Final Result: **1:60**

_Revised Function Example:_
Minutes = 119.7 / 60 = 1.995 = Math.floor(1.995) = 1
Seconds = 119.7 % 60 = 59.7 = Math.**floor**(59.7)) = 59
Final Result: **1:59**

Using floor will mean we ignore fractions of seconds, but seems like for the apps purposes that won't really matter here.  Issue should close when "easy-issues" is pulled into master.

**Comment by jimfellows-NOAA** [comment] 2021-07-08 14:52
Closing issue.  Fix is currently on develop-hlmatrix

**Closed by jimfellows-NOAA** 2021-07-08 14:52 UTC
Labels: H&L, HookMatrix, easy?
